version: '3.7'

services:
    fastapi:
      env_file:
        - ./src/app/.env_example
      build:
        context: .
        dockerfile: Dockerfile
      environment:
        REDIS_HOST: redis
        POSTGRES_SERVER: pdb
      depends_on:
        - pdb
      ports:
        - "80:80"
    pdb:
      image: postgres:alpine
      restart: on-failure
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
      volumes:
        - ./data/pgdata:/var/lib/postgresql/data
    redis:
      image: redis
      restart: on-failure
      volumes:
        - ./data/redis-data:/data


